# Taps
tap 'caskroom/cask'
tap 'homebrew/homebrew-php'

brew 'ansible'
brew 'bash'
brew 'coreutils'
brew 'findutils'
brew 'grep'
brew 'htop'
brew 'imagemagick'
brew 'lxc'
brew 'mackup'
brew 'mariadb'
brew 'mas'
brew 'php72'
brew 'telnet'
brew 'terraform'
brew 'terraform-inventory'
brew 'thefuck'
brew 'wp-cli'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'authy'
cask 'bettertouchtool'
cask 'caffeine'
cask 'dropbox'
cask 'google-chrome'
cask 'iterm2'
cask 'keybase'
cask 'phpstorm'
cask 'postman'
cask 'psequel'
cask 'sequel-pro'
cask 'slack'
cask 'spotify'
cask 'stack'
cask 'sublime-text'
cask 'toggl'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'

mas 'Spark', id: 1176895641
